import type { Metadata } from 'next';
import { ColorModeScript, CSSReset, Grid, GridItem } from '@chakra-ui/react';
import { Providers } from './providers';
import StoreProvider from './StoreProvider';
import Navigation from '@/components/Sidebar/Navigation';
import Header from '@/components/Header/Header';
import { fonts } from './fonts';
import theme from './theme';
import Footer from '@/components/Footer/Footer';

export const metadata: Metadata = {
  title: 'KeepIt',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang='en' className={fonts.rubik.variable}>
        <body>
          <ColorModeScript initialColorMode={theme.config.initialColorMode} />
          <Providers>
            <CSSReset />
            <Grid
              // templateAreas={`"header header"
              //     "nav main"
              //     "footer footer"`}

              templateAreas={{
                md: `"header header"
                           "nav main"
                           "footer footer"`,
                base: `"header header"
                           "main main"
                           "footer footer"`,
              }}
              gridTemplateRows={'auto 1fr 100px'}
              gridTemplateColumns={'auto 1fr'}
              h='100vh'
              gap='1'
            >
              <GridItem padding='5px' area={'header'}>
                <Header />
              </GridItem>
              <GridItem
                pl='2'
                area={'nav'}
                display={{ base: 'none', md: 'flex' }}
              >
                <Navigation />
              </GridItem>
              <GridItem
                area={'main'}
                display='flex'
                justifyContent='center'
                overflow='scroll'
                maxH='1000px'
              >
                {children}
              </GridItem>
              <GridItem pl='2' area={'footer'}>
                <Footer />
              </GridItem>
            </Grid>
          </Providers>
        </body>
      </html>
    </StoreProvider>
  );
}
