import type { Metadata } from 'next';
import { Providers } from './providers';
import { fonts } from './fonts';
import { ColorModeScript, CSSReset } from '@chakra-ui/react';
import theme from './theme';
import StoreProvider from './StoreProvider';

export const metadata: Metadata = {
  title: 'KeepIt',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang='en' className={fonts.rubik.variable}>
        <body>
          <ColorModeScript initialColorMode={theme.config.initialColorMode} />
          <Providers>
            <CSSReset />
            {children}
          </Providers>
        </body>
      </html>
    </StoreProvider>
  );
}
